# Generated by Django 2.1.5 on 2019-02-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mapa',
            new_name='map_data_base',
        ),
    ]
